### ISSUE TITLE
The side menu in ProLayout stayed on the left when the design is from right to left🐛[BUG]

### ISSUE THREAD

**Issue by abdelrazzaq-dev** [ant-design/pro-components#3303]
When I change the language of the application Arabic which is from right to left the side menu stayed on the left though the design did shift to the right to left mentality.
You can check this Bug on the [pro preview design website](https://preview.pro.ant.design/) when the language is set to Farsi (IR)

**Comment by chenshuai2144** [comment]
> TAutomatically replying with ChatGPT can be attempted, but it cannot be guaranteed to be completely accurate and may not fully address all issues. Please feel free to reply if you have any further questions or concerns.
 > 此回复基于 ChatGPT 自动生成，可以尝试下方案，官方人员会在一定时间后继续继续处理。


Thank you for reaching out with your issue. It looks like the side menu in `ProLayout` isn't properly shifting to the right when the language is set to a right-to-left layout, such as Arabic or Farsi. 

One way to solve this issue is by setting the `direction` CSS property to `rtl` on the specific element that isn't shifting. In this case, it seems like the `SiderMenu` component of `ProLayout` is the element that needs this property set. 

You can try this code snippet to add the `direction: rtl` property to the `SiderMenu`:

```css
.ant-pro-sider-menu {
  direction: rtl;
}
```

You can add this code either in a separate CSS file or in-line in the component itself.

I hope this helps! Let me know if you need further assistance.

**Comment by chenshuai2144** [comment]
在新版本的layout中已经默认支持了
