### ISSUE TITLE
ProTable Toolbar Customization with action buttons on the left 

### ISSUE THREAD

**Issue by trafreider** [ant-design/pro-components#3978]
Dear developers,

I really love ProTable. By default the toolbar's action buttons are aligned on the right. I would like to have the option to align on the left. This is helpful and more user-friendly on extra large screens that display a full-width table. Assuming that you read from left to right, the advantage is that you have to go for shorter distances with you mouse.

**Comment by LeQuy-123** [comment]
I put the action button inside headerTitle instead of toolBarRender

**Comment by chenshuai2144** [comment]
> TAutomatically replying with ChatGPT can be attempted, but it cannot be guaranteed to be completely accurate and may not fully address all issues. Please feel free to reply if you have any further questions or concerns.
 > 此回复基于 ChatGPT 自动生成，可以尝试下方案，官方人员会在一定时间后继续继续处理。


To achieve the desired result of putting the action buttons on the left side of the ProTable toolbar, you can use the `headerTitle` property instead of `toolBarRender`. `headerTitle` allows you to customize the table header section with your own React component. Here's an example code snippet:

```jsx
import React from 'react';
import ProTable from '@ant-design/pro-table';

const columns = [
  {
    title: 'Name',
    dataIndex: 'name',
    key: 'name',
  },
  {
    title: 'Email',
    dataIndex: 'email',
    key: 'email',
  },
  {
    title: 'Age',
    dataIndex: 'age',
    key: 'age',
  },
];

const data = [
  {
    key: '1',
    name: 'John Doe',
    email: 'johndoe@example.com',
    age: 32,
  },
  {
    key: '2',
    name: 'Jane Smith',
    email: 'janesmith@example.com',
    age: 25,
  },
];

const MyTable = () => {
  const renderToolbar = () => {
    return <div>Some custom content on the right</div>;
  };

  const renderHeaderTitle = () => {
    return (
      <div style={{ display: 'flex', justifyContent: 'flex-start', alignItems: 'center' }}>
        <div style={{ marginRight: '20px' }}>Some custom content on the left</div>
        <div>{renderToolbar()}</div>
      </div>
    );
  };

  return (
    <ProTable
      columns={columns}
      dataSource={data}
      headerTitle={renderHeaderTitle}
    />
  );
};

export default MyTable;
```

In this example, we define a new function called `renderHeaderTitle` which returns a custom component with two `<div>`s that are arranged side by side using `display: 'flex'`. The first `<div>` contains the action buttons we want to put on the left of the toolbar. The second `<div>` contains the existing custom content we want to show on the right. Finally, we pass `renderHeaderTitle` to `headerTitle` property on the `ProTable` component.
