### ISSUE TITLE
🐛[BUG] ProTable select fieldProps.options not updating

### ISSUE THREAD

**Issue by askurat** [ant-design/pro-components#4025]
### 🐛 bug

I am trying to set my select options based on my data being loaded in the table.  I have even tried using renderFormItem but can't seem to set fieldProps.options.

I did notice when trying to use renderFormItem, it seems to acutally hit this function twice. The first time my data is there, the second time it is gone. I created a reproduction of this.

### 📷 

If you simulate a promise  to get the data for fieldProps.options, you'll notice if you select the dropdown there aren't any options. It seems to never re-render the dropdown properly. 

### 🏞

Previously I would just set fieldProps.options with the data I wanted once it was loaded. This seemed to work fine but now it seems to be broke or some functionality has changed.

### 💻

https://codesandbox.io/s/qing-liang-shai-xuan-ti-huan-cha-xun-biao-dan-forked-b3xim?file=/App.tsx

### ©

- ProComponents: "@ant-design/pro-table": "2.56.9"

**Comment by chenshuai2144** [comment]
The table does not know that the option has been updated, so it caches the configuration of the column. If you need it, I recommend that you use request to refresh the select in the table

**Comment by askurat** [comment]
Unless I am missing something, this still does not work. I updated the sandbox: https://codesandbox.io/s/qing-liang-shai-xuan-ti-huan-cha-xun-biao-dan-forked-ebldt?file=/App.tsx

**Comment by chenshuai2144** [comment]
Thanks for your persistent reply, it seems that the update was blocked by the table. I will find the problem and fix it quickly.

I will reply you.

**Comment by askurat** [comment]
Any update on this?

**Comment by chenshuai2144** [comment]
> TAutomatically replying with ChatGPT can be attempted, but it cannot be guaranteed to be completely accurate and may not fully address all issues. Please feel free to reply if you have any further questions or concerns.
 > 此回复基于 ChatGPT 自动生成，可以尝试下方案，官方人员会在一定时间后继续继续处理。


Apologies for the delay in responding. We have identified the issue and it appears to be a bug. The fieldProps.options are only passed once to the form using the current logic. There are a couple of workaround solutions that you can try as follows:

### Solution 1:

You can remove `fieldProps.options` from the renderFormItem and instead use a `select` in the customRender of ProTable. Then, you can set the options there:

```tsx
{
  title: "Creator",
  dataIndex: "creator",
  valueType: "select",
  renderFormItem: () => null,
  render: (_, record) => (
    <Select
      value={record.creator}
      options={options}
      onChange={(value: string) => update(record.id, value)}
    />
  )
}
```

### Solution 2:

You can pass a unique key prop to the `Protable` so that it re-renders and calls the `renderFormItem` prop function. You can use something like `key={data.length}`. The `data` variable should be the same as the one passed to the `dataSource` prop.

```tsx
<ProTable<TableListItem>
  columns={columns}
  dataSource={data}
  key={data.length} // added key prop here
  options={{
    search: { name: "name", placeholder: "Name" }
  }}
/>
```

I hope one of these solutions works for you. Feel free to ask any follow-up questions.
