### ISSUE TITLE
🧐[问题]嵌套子表头如何支持显/隐

### ISSUE THREAD

**Issue by zhouzhiyang-git** [ant-design/pro-components#416]
### 🧐 问题描述
按照正常的配置，setting中只有一级表头，如何生成二级表头显示隐藏
{
      title: '一级',
      align: 'center',
      children: [
        {
          title: '二级',
          dataIndex: 'dl_src',
          align: 'center',
        }
     ]
}

**Comment by chenshuai2144** [comment]
暂时还不支持

**Comment by chenshuai2144** [comment]
已经支持

**Comment by chenweisheng01** [comment]
看了上面答案说已经支持，怎么感觉支持两层列合并是可以的， 但是当pro-table表头有三层及以上列合并的情况下列设置控件显示隐藏列的逻辑混乱
1.勾选和取消无效 一直处于选中状态
2.层级嵌套显示不完全

**Comment by chenshuai2144** [comment]
@chenweisheng01  来个issue，给个重现。

**Comment by chenweisheng01** [comment]
------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "ant-design/pro-components"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2021年11月14日(星期天) 中午11:33
***@***.***&gt;;
***@***.******@***.***&gt;;
主题:&nbsp;Re: [ant-design/pro-components] 🧐[问题]嵌套子表头如何支持显/隐 (#416)





 
@chenweisheng01  来个issue，给个重现。
 
—
You are receiving this because you were mentioned.
Reply to this email directly, view it on GitHub, or unsubscribe.
Triage notifications on the go with GitHub Mobile for iOS or Android.
