### ISSUE TITLE
🐛[BUG]可编辑表格的日期列，获取格式化数据时没按照指定的日期格式

### ISSUE THREAD

**Issue by cui-xxu** [ant-design/pro-components#6377]
提问前先看看：

https://github.com/ryanhanwu/How-To-Ask-Questions-The-Smart-Way/blob/main/README-zh_CN.md

### 🐛 bug 描述

可编辑表格的日期列，用fieldProps.format指定了日期格式，但是使用form的getFieldsFormatValue和table的getRowsData获取数据时，拿到的都是标准时间格式的数据，不是指定的日期格式

### 📷 复现步骤

样例代码中，点击“获取table数据”查看提示信息、点击“提交”查看控制台

### 🏞 期望结果

日期列updDate按照指定的日期格式进行格式化

### 💻 复现代码

import { useRef } from 'react';
import { message, Button } from 'antd';
import type { ProFormInstance} from '@ant-design/pro-form';
import { ProForm } from '@ant-design/pro-form';
import type { EditableFormInstance, ProColumns } from '@ant-design/pro-table';
import { EditableProTable } from '@ant-design/pro-table';

const BasicTest: React.FC = () => {
  const formRef = useRef<ProFormInstance>();

  // 可维护列表
  type TestModel = {
    rowIndex: number;
    code: string;
    name: string;
    updDate?: string;
    desc: string;
  };
  const columns: ProColumns<TestModel>[] = [
    {
      title: '代码',
      dataIndex: 'code',
      formItemProps: {
        rules: [{ required: true }],
      },
    },
    {
      title: '名称',
      dataIndex: 'name',
    },
    {
      title: '修改日期',
      dataIndex: 'updDate',
      valueType: 'date',
      fieldProps: {
        format: 'YYYYMMDD',
      }
    },
    {
      title: '说明',
      dataIndex: 'desc',
    },
    {
      title: '操作',
      valueType: 'option',
      width: 200,
      render: (_1, record, _2, action) => [
        <a
          key="editable"
          onClick={() => {
            const obj: any = action;
            if (obj.editableKeys.length <= 0) {
              action?.startEditable?.(record.rowIndex || 0);
            } else {
              message.warning('存在正在编辑行，请完成正在编辑行');
            }
          }}
        >
          编辑
        </a>,
      ],
    },
  ];
  const dataSource: TestModel[] = [
    { rowIndex: 2, code: 'code1', name: 'name1', desc: 'desc1' },
    { rowIndex: 3, code: 'code2', name: 'name2', desc: 'desc2' },
  ];
  // 可编辑表格form使用样例
  const editorFormRef = useRef<EditableFormInstance<TestModel>>();

  return (
            <ProForm<{
              table: TestModel[];
            }>
              initialValues={{
                table: dataSource,
              }}
              validateTrigger="onBlur"
              formRef={formRef}
              onFinish={async () => {
                console.log(formRef.current?.getFieldsFormatValue?.());
              }}
            >
              <EditableProTable<TestModel>
                name="table"
                rowKey="rowIndex"
                toolBarRender={() => [
                  <Button
                    key="rows"
                    onClick={() => {
                      const rows = editorFormRef.current?.getRowsData?.();
                      alert(JSON.stringify(rows));
                    }}
                  >
                    获取 table 的数据
                  </Button>,
                ]}
                columns={columns}
                editableFormRef={editorFormRef}
                recordCreatorProps={{
                  record: () => {
                    return {
                      rowIndex: Date.now(),
                    } as unknown as TestModel;
                  },
                }}
                editable={{
                  saveText: '确定',
                }}
              />
            </ProForm>
  );
};

export default BasicTest;

### © 版本信息

- ProComponents 版本:2.3.46
- umi 版本
- 浏览器环境
- 开发环境 [e.g. mac OS]

**Comment by chenshuai2144** [comment]
> TAutomatically replying with ChatGPT can be attempted, but it cannot be guaranteed to be completely accurate and may not fully address all issues. Please feel free to reply if you have any further questions or concerns.
 > 此回复基于 ChatGPT 自动生成，可以尝试下方案，官方员会在一定时间后继续继续处理。


（中英文版本，请根据您的阅读习惯选择阅读）

（English version is followed by the Chinese version）

---

你好，@cui-xxu，感谢你提供这个问题。

这个问题可能是由于 `getFieldsValue`、`getFieldsFormatValue` 以及 `getRowsData` 的行为机制所导致的。

`getFieldsValue` 和 `getFieldsFormatValue` 返回的都是键值对对象，其中的值是经过 antd 的内置处理后的值。在 antd 的 `DatePicker` 组件中，它的取值规则是格式化后的字符串时间值。因此，你可以修改你的 `onFinish` 回调函数，用 `getFieldsValue(true)` 获取未经过 antd 内置处理的原始数据值。

而在 `getRowsData` 中，每行数据的取值规则也是经过 antd 的内置处理的。你可以修改获取每行数据的回调函数，以便你在返回每行数据的时候，显式地将这一行数据中的日期属性转换成格式化后的字符串时间值。

代码的修改建议如下：

```jsx
import { useRef } from 'react';
import { message, Button } from 'antd';
import type { ProFormInstance } from '@ant-design/pro-form';
import { ProForm } from '@ant-design/pro-form';
import type { EditableFormInstance, ProColumns } from '@ant-design/pro-table';
import { EditableProTable } from '@ant-design/pro-table';

const BasicTest: React.FC = () => {
  const formRef = useRef<ProFormInstance>();

  // 可维护列表
  type TestModel = {
    rowIndex: number;
    code: string;
    name: string;
    updDate?: string;
    desc: string;
  };
  const columns: ProColumns<TestModel>[] = [
    {
      title: '代码',
      dataIndex: 'code',
      formItemProps: {
        rules: [{ required: true }],
      },
    },
    {
      title: '名称',
      dataIndex: 'name',
    },
    {
      title: '修改日期',
      dataIndex: 'updDate',
      valueType: 'date',
      fieldProps: {
        format: 'YYYYMMDD',
      },
    },
    {
      title: '说明',
      dataIndex: 'desc',
    },
    {
      title: '操作',
      valueType: 'option',
      width: 200,
      render: (_1, record, _2, action) => [
        <a
          key="editable"
          onClick={() => {
            const obj: any = action;
            if (obj.editableKeys.length <= 0) {
              action?.startEditable?.(record.rowIndex || 0);
            } else {
              message.warning('存在正在编辑行，请完成正在编辑行');
            }
          }}
        >
          编辑
        </a>,
      ],
    },
  ];

  const dataSource: TestModel[] = [
    { rowIndex: 2, code: 'code1', name: 'name1', desc: 'desc1' },
    { rowIndex: 3, code: 'code2', name: 'name2', desc: 'desc2' },
  ];

  // 可编辑表格form使用样例
  const editorFormRef = useRef<EditableFormInstance<TestModel>>();

  return (
    <ProForm<{
      table: TestModel[];
    }>
      initialValues={{
        table: dataSource,
      }}
      validateTrigger="onBlur"
      formRef={formRef}
      onFinish={async (values) => {
        console.log(values);
        // console.log(formRef.current?.getFieldsValue?.(true)); // 触发ant的字段值处理，因此updDate字段值是处理后的，不是格式化值
      }}
    >
      <EditableProTable<TestModel>
        name="table"
        rowKey="rowIndex"
        toolBarRender={() => [
          <Button
            key="rows"
            onClick={() => {
              const rows = editorFormRef.current?.getRowsData?.((record) => {
                return {
                  ...record,
                  updDate: record.updDate
                    ? moment(record.updDate).format('YYYYMMDD')
                    : undefined,
                };
              });
              alert(JSON.stringify(rows));
            }}
          >
            获取 table 的数据
          </Button>,
        ]}
        columns={columns}
        editableFormRef={editorFormRef}
        recordCreatorProps={{
          record: () => {
            return {
              rowIndex: Date.now(),
            } as unknown as TestModel;
          },
        }}
        editable={{
          saveText: '确定',
        }}
      />
    </ProForm>
  );
};

export default BasicTest;
```

其他，请参阅 antd 的官方文档关于 [DatePicker](https://ant.design/components/date-picker-cn/#header) 和 [ProTable](https://procomponents.ant.design/components/table-cn/).

希望以上信息对你有所帮助！

---

Hello, @cui-xxu, thank you for submitting this issue.

The issue you encountered is probably caused by the behavior of `getFieldsValue`, `getFieldsFormatValue`, and `getRowsData`.

Both `getFieldsValue` and `getFieldsFormatValue` return key-value pairs, whose values are processed by the built-in antd mechanism. In antd's `DatePicker` component, the value-taking mechanism is the formatted string time value. Therefore, you can modify your `onFinish` callback function to get the original value that has not been processed by antd, by using `getFieldsValue(true)`.

In `getRowsData`, the value-taking mechanism of each row of data is also processed by antd. You can modify the callback function that gets each row of data, so that when you return each row of data, you can explicitly convert the date attribute in this row of data into a formatted string time value.

Here is the suggested modification of your code:

(See above in the Chinese version of this response)

For more information, please refer to the official documentation of [DatePicker](https://ant.design/components/date-picker/) and [ProTable](https://procomponents.ant.design/components/table/).

Hope the above information will help you!

**Comment by chenshuai2144** [comment]
修复了，因为dayjs 的版本重复导致的
