### ISSUE TITLE
🧐[问题]关于ProLayout的部分token不生效的问题

### ISSUE THREAD

**Issue by splitter12138** [ant-design/pro-components#6583]
### 🧐 问题描述

我设置了 ProLayout 的token 为 slider 设置新的样式，但是我发现 `colorTextMenuActive` 和 `colorBgMenuItemHover` 并没有正确的工作。
对于 `colorTextMenuActive` ，按官网文档的解释它表示「menuItem hover 的选中字体颜色」，我的理解是「处于 selected 状态的 menu Item 鼠标悬停时的文字颜色」。但实际情况是「处于 selected 状态的 menu Item 鼠标悬停时」使用的是 `colorTextMenuItemHover` 所设置的颜色。
对于 `colorBgMenuItemHover` 以及`colorBgMenuItemCollapsedHover` 来说它们没有任何作用。

我不清楚是我理解上的问题还是说这真的是一个BUG。

望答复：）

**Comment by hesetiema** [comment]
same issue.

**Comment by chenshuai2144** [comment]
> TAutomatically replying with ChatGPT can be attempted, but it cannot be guaranteed to be completely accurate and may not fully address all issues. Please feel free to reply if you have any further questions or concerns.
 > 此回复基于 ChatGPT 自动生成，可以尝试下方案，官方员会在一定时间后继续继续处理。


### 🌈 解决方案

根据您的描述，很有可能是你的理解上存在一些问题造成的，这些 token 的作用描述确实有一些绕口。

首先来说说 `colorTextMenuActive`。它的作用是设置「菜单项文字颜色（已选中）」。其中选中是指当前页面所处的菜单项，而不是鼠标悬停在某个菜单项上。因此，当你想要改变处于选中状态的菜单项的字体颜色时，应该使用 `colorTextMenuActive`。对于其它状态下的菜单项字体颜色设置，可以使用 `colorTextMenuItemHover`。 所以，针对这个问题，建议您修改 token 为：

```css
//改用 colorTextMenuHover 以改变鼠标悬停在菜单项上的字体颜色
@colorTextMenuHover: #1890ff;

//处于 selected 状态的 menu Item 的字体颜色
@colorTextMenuActive: #fff;

//菜单项鼠标悬停时的字体颜色
@colorTextMenuItemHover: #fff;
```

接着来看看 `colorBgMenuItemHover` 和 `colorBgMenuItemCollapsedHover`，这两个 token 确实没有任何作用。这是因为 ProLayout 的菜单项背景色是使用 `@layout-body-background` 来设置的。如果您想要改变菜单项在 hover 状态和 collapsed 状态下的背景颜色的话，可以重写以下 class 来实现：

```css
.ant-menu-item:hover {
  background-color: @菜单项背景颜色
}

.ant-menu-item-selected {
  background-color: @菜单项背景颜色;
  &:hover {
    background-color: @菜单项hover时背景颜色;
  }
}

.ant-menu-item-selected.ant-menu-item-collapsed {
  background-color: @菜单项collapsed时背景颜色;
  &:hover {
    background-color: @菜单项collapsed时hover时背景颜色;
  }
}
```

最后如果需要查看更多关于 Ant Design ProLayout 的用法，可以参考官方文档：[https://pro.ant.design/components/layout-cn/](https://pro.ant.design/components/layout-cn/)。

**Comment by chuanhhoang** [comment]
This answer is incorrect. Too many problems with the latest Ant Design Pro.

**Comment by chenshuai2144** [comment]
> TAutomatically replying with ChatGPT can be attempted, but it cannot be guaranteed to be completely accurate and may not fully address all issues. Please feel free to reply if you have any further questions or concerns.
 > 此回复基于 ChatGPT 自动生成，可以尝试下方案，官方人员会在一定时间后继续继续处理。


I'm sorry that my previous answer didn't solve your issue. Could you please provide more information about your problem? What specifically isn't working for you with the latest version of Ant Design Pro? I'd be happy to try and help you find a solution.

**Comment by chuanhhoang** [comment]
<img width="1728" alt="Screenshot 2023-03-08 at 17 48 44" src="https://user-images.githubusercontent.com/19351207/223693702-b92912a0-1a75-4b30-9351-ec126b2432fe.png">
With the following tokens:

```
  token: {    
    sider: {
      colorMenuBackground: 'white',
      colorMenuItemDivider: '#dfdfdf',
      colorBgMenuItemHover: 'red',
      colorTextMenu: '#595959',
      colorTextMenuSelected: 'red',
      colorTextMenuActive: '#242424',
...
```

I expect the background color of the hovered menu item to be "red" but as clearly see in the screenshot, the color is the default gray.

**Comment by chenshuai2144** [comment]
> TAutomatically replying with ChatGPT can be attempted, but it cannot be guaranteed to be completely accurate and may not fully address all issues. Please feel free to reply if you have any further questions or concerns.
 > 此回复基于 ChatGPT 自动生成，可以尝试下方案，官方人员会在一定时间后继续继续处理。


### 🧐 Problem description

Based on your description and the provided screenshot, it looks like you are trying to set the `colorBgMenuItemHover` token to `red` in order to change the background color of a hovered menu item in Ant Design, but it does not seem to be working.

### 🌈 Solution

From your token configurations, it appears that the issue may be with the ordering of your `global.less` file, as the token values appear to be correct. Try the following:

1. Make sure that you have imported the Ant Design theme into your project and that the `@import` statement comes before your own styles in the `global.less` file.

2. If that doesn't solve the issue, try updating the token to `@primary-color` rather than `colorBgMenuItemHover`, which should change the background color of the item when it is selected.

3. If you want to specifically target the background color of a hovered menu item, try something like the following code:

```css
.ant-menu-item:hover {
  background-color: red;
}
```

4. If you want to target the background color of a selected menu item, try the following:

```css
.ant-menu-item-selected {
  background-color: red;
}
```

If the above steps do not solve the problem, it is possible that there could be another rule or style that is overriding your styles. In that case, try using the browser's developer tools to inspect the element and see what styles are currently being applied to it.

For more information on styling Ant Design menus, you can check out their documentation: [Ant Design Menu](https://ant.design/components/menu/).

**Comment by daifuyang** [comment]
same issue

**Comment by hungtcs** [comment]
Same issues, all tokens in <https://procomponents.ant.design/components/layout#header-token> do not take effect at all.



- https://codesandbox.io/s/ji-chu-shi-yong-forked-pio434?file=/App.tsx

**Comment by 5201314999** [comment]
same issue

**Comment by chenshuai2144** [comment]
修复了，antd 改了token导致的

**Comment by wangwufan** [comment]
> 修复了，antd 改了token导致的

现在仍有问题，PageContainer里如果再次动态加载带有Menu组件的页面，Prolayout的菜单的一部分样式又会被覆盖，弹出菜单变回默认的白底黑字，标题菜单文字颜色直接和背景一样了
