### ISSUE TITLE
Missing Slovak and Czech translation

### ISSUE THREAD

**Issue by craftedsro** [ant-design/pro-components#6801]
I got same problem as [EugeneGohh:fix/thai-translation-not-working](https://github.com/EugeneGohh/pro-components/tree/fix/thai-translation-not-working)

Translation did not work.

**Comment by chenshuai2144** [comment]
> TAutomatically replying with ChatGPT can be attempted, but it cannot be guaranteed to be completely accurate and may not fully address all issues. Please feel free to reply if you have any further questions or concerns.
 > 此回复基于 ChatGPT 自动生成，可以尝试下方案，官方人员会在一定时间后继续继续处理。


Sorry, I'm an AI language model and I cannot access external links or repositories. However, for translations in a React project, there are multiple solutions depending on the library or tool used for translations. Here are some general tips to solve the issue:

1. Check that the translation files exist: Make sure that the translations for Slovak and Czech are present in the translation files. If not, add them following the same format as the other translations.

2. Verify the language codes: Ensure that the language codes for Slovak and Czech are correct. The language code for Slovak is `sk` and for Czech is `cs`.

3. Set the language code: In the component or page where the translated text should appear, set the language code to the desired language. For example, if you're using `react-i18next`, you can set the language code in the `i18n` object like this:

```
import i18n from 'i18next';
import { initReactI18next } from 'react-i18next';

// ...

i18n.use(initReactI18next).init({
  resources: {
    en: { translation: { /* ... */ } },
    sk: { translation: { /* ... */ } },
    cs: { translation: { /* ... */ } },
  },
  lng: 'en', // Set default language here
  // ...
});
```

4. Use the `Trans` component: Instead of using plain text in your JSX, use the `Trans` component from `react-i18next` to enable translations:

```
import { Trans } from 'react-i18next';

function MyComponent() {
  return (
    <div>
      <Trans i18nKey="my.translation.key">
        <strong>Hello</strong>, <em>world</em>!
      </Trans>
    </div>
  );
}
```

5. Use the translation key: Make sure that the translation key used in the component matches the translation key in the translation file. For example:

```
// Translation file
{
  "my.translation.key": "Hello, world!",
  // ...
}

// Component
function MyComponent({ t }) {
  return (
    <div>{t('my.translation.key')}</div>
  );
}
```

Remember, these are general guidelines and might not solve your specific issue. Always consult the documentation of the library or tool you're using for translations for more specific solutions.

**Comment by chenshuai2144** [comment]
close by https://github.com/ant-design/pro-components/pull/6802
