### ISSUE TITLE
Style tags of pro-components are automatically appended to head

### ISSUE THREAD

**Issue by alicanso** [ant-design/pro-components#7264]
### 🧐 Problem Description

Although I use cssinjs with the latest Antd and I define "container" in StyleProvider, style tags of pro-components are appended to head. I am using shadow dom and I need these styles inside my shadow dom.

Is it a planned feature or a bug? Or am I missing something?

**Comment by chenshuai2144** [comment]
> TAutomatically replying with ChatGPT can be attempted, but it cannot be guaranteed to be completely accurate and may not fully address all issues. Please feel free to reply if you have any further questions or concerns.
 > 此回复基于 ChatGPT 自动生成，可以尝试下方案，官方人员会在一定时间后继续继续处理。


### 🤔 Problem Analysis

Based on your description, it seems that when using Ant Design's pro-components along with cssinjs and a StyleProvider, the styles for the pro-components are automatically appended to the `<head>` element instead of being contained within your shadow DOM. You would like to know if this behavior is intentional or if there's a way to have the styles applied within the shadow DOM.

### 👉 Solution

Ant Design pro-components utilize CSS modules for styling. By default, CSS modules generate unique class names for each component, ensuring scoping and preventing style conflicts. However, due to the nature of CSS modules and their classes, the styles need to be injected into the `<head>` element for them to take effect.

To solve this issue and have the styles applied within your shadow DOM, you can use a custom CSS-in-JS solution that supports styling within the shadow DOM, such as `styled-components` or `emotion`. These libraries are compatible with React and provide the ability to create components with encapsulated styles.

Here's an example using `styled-components`:

1. Install the necessary dependencies:

```bash
npm install styled-components
```

2. Wrap your pro-components with `styled-components` and pass the necessary styles:

```jsx
import React from 'react';
import { Menu } from 'antd';
import styled from 'styled-components';

const StyledMenu = styled(Menu)`
  /* Your custom styles here */
`;

const MyComponent = () => {
  return (
    <div>
      <StyledMenu />
    </div>
  );
};

export default MyComponent;
```

By using `styled-components`, the styles for the `Menu` component are encapsulated within the component itself and will be rendered inside your shadow DOM.

### 📚 Documentation

- [CSS modules](https://github.com/css-modules/css-modules)
- [styled-components](https://styled-components.com/)
- [emotion](https://emotion.sh/)
- [Ant Design pro-components](https://procomponents.ant.design/)
- [Ant Design customizing theme](https://ant.design/docs/react/customize-theme)

**Comment by shanmugarajbe** [comment]
Still, this issue exists and cssinjs is not working for Antd Pro components with shadow dom. Is there any workaround available for this issue?
