### ISSUE TITLE
ProTable onDataSourceChange wrong typescript 🐛[BUG]

### ISSUE THREAD

**Issue by matteomaiocchi99** [ant-design/pro-components#7353]
Good morning, I noticed that there is an error in the typing of the `onDataSourceChange` prop of the `ProTable` component: according to the code typing (and also the documentation), the function should receive only one prop, namely `dataSource`, but in reality, two different `dataSource` are being passed. 
Thank you for your support.

ant-design/pro-components => version 2.6.2

**Comment by chenshuai2144** [comment]
> TAutomatically replying with ChatGPT can be attempted, but it cannot be guaranteed to be completely accurate and may not fully address all issues. Please feel free to reply if you have any further questions or concerns.
 > 此回复基于 ChatGPT 自动生成，可以尝试下方案，官方人员会在一定时间后继续继续处理。


Hi there,

Thank you for reaching out to us about the issue with the `onDataSourceChange` prop in `ProTable` component. I apologize for the inconvenience caused.

Looking at the code and documentation, it seems that there is a discrepancy with the typing. I understand that you are encountering a situation where two different `dataSource` objects are being passed instead of just one.

To resolve this issue, you can try the following steps:

1. Verify that you are using the correct version of `ant-design/pro-components`. As of now, version 2.6.2 is the latest.

2. If you are using TypeScript, you can manually type the `onDataSourceChange` prop to accept two arguments, as shown below:

```tsx
import { ProColumns, ProTableProps } from 'ant-design/pro-table';

interface YourDataItemType {
  // Define your data item type here
}

const columns: ProColumns<YourDataItemType>[] = [...];

const YourComponent: React.FC = () => {
  const handleDataSourceChange = (newDataSource: YourDataItemType[], action: 'add' | 'update' | 'delete') => {
    // Handle the dataSource change here based on the action
  };

  return (
    <ProTable<YourDataItemType>
      columns={columns}
      onDataSourceChange={handleDataSourceChange}
      // other props
    />
  );
};
```

By manually typing the prop, you can now handle the `newDataSource` and `action` separately in the `handleDataSourceChange` callback function.

3. If you find that even after the above steps, the issue persists, I would recommend opening an issue on the official GitHub repository of `ant-design/pro-components`. This will allow the maintainers to further investigate the problem and provide a more permanent solution.

I hope this helps! Let me know if you have any further questions.
